#ifndef PINS_H
#define PINS_H

#include <Arduino.h>

#define MPIN_BUZZER PA12
#define MPIN_LED PB3
#define MPIN_RELE1 PA11
#define MPIN_RELE2 PA15
#define MPIN_MED_CORRIENTE PA7

#define MPIN_PWM_HBRIDGE_LV1 PB0
#define MPIN_PWM_HBRIDGE_LV2 PB4
#define MPIN_PWM_HBRIDGE_LV3 PB5

#define MPIN_SDA PB7
#define MPIN_SCL_ PB6

#define  MPIN_POSICION_ENTINTADOR PA6

#define MPIN_IN_BTN1 PB1
#define MPIN_IN_BTN2 PA5
#define MPIN_IN_BTN3 PA4
#define MPIN_IN_BTN4 PB15

//Steppers

#define MPIN_STEPPER_STEP1 PB9
#define MPIN_STEPPER_DIR1 PA8
#define MPIN_STEPPER_ENABLE PB14

#define MPIN_STEPPER_STEP2 PB8
#define MPIN_STEPPER_DIR2 PB13



 


#endif